### ISSUE TITLE
obsidian v1.7.2 incompatibilities

### ISSUE THREAD

**Issue by baodrate** [TfTHacker/obsidian42-strange-new-worlds#148]
Lots of errors with [Obsidian v1.7.2](https://obsidian.md/changelog/2024-09-19-desktop-v1.7.2/) (and later), e.g.

```
Uncaught TypeError: Cannot read properties of undefined (reading 'path')
    at getSNWCacheByFile (plugin:obsidian42-strange-new-worlds:113:34)
    at processFrontmatterLinks (plugin:obsidian42-strange-new-worlds:5071:28)
    at eval (plugin:obsidian42-strange-new-worlds:5055:49)
    at t.iterateLeaves (app.js:1:2295515)
    at t.iterateLeaves (app.js:1:2295613)
    at t.iterateLeaves (app.js:1:2295613)
    at t.iterateAllLeaves (app.js:1:2295777)
    at setFrontmatterLinksReferenceCounts (plugin:obsidian42-strange-new-worlds:5054:26)
    at eval (plugin:obsidian42-strange-new-worlds:5060:5)
    at l (app.js:1:518110)
```

for [reference](https://docs.obsidian.md/Plugins/Guides/Understanding+deferred+views):

> As of Obsidian v1.7.2, When Obsidian loads, all views are created as instances of DeferredView. Once a view is visible on screen (i.e. the tab is selected within its containing tab group), the leaf will rerender and the view will be switched out to the correct View instance.

**Comment by ksdavidc** [comment]
me too. does not happen for me in sandbox, though.

**Comment by wwjCMP** [comment]
+1

**Comment by PlayerMiller109** [comment]
<img width="400" src="https://github.com/user-attachments/assets/70dc6512-b519-436a-bf25-fd941926ef3a">

I changed this part in the main.js, seems to work for me.

```js
setTimeout(async () => {
  const leaf = this.app.workspace.getLeavesOfType(VIEW_TYPE_SNW)[0]
  if (!leaf) {
    await this.app.workspace.getRightLeaf(false).setViewState({ type: VIEW_TYPE_SNW, active: false });
  } else await leaf.loadIfDeferred()
  buildLinksAndReferences();
})
```
